{ referrals: { granted: 0, used: 0 },
  subscriptions: [],
  muted_topics: [],
  email_dict: {},
  last_event_id: -1,
  alert_words: [],
  max_message_id: 13199301,
  result: 'success',
  presences: 
   { 'adam@adampash.com': { website: [Object] },
     'pfrance@gmail.com': { website: [Object] },
     'darius@wry.me': { website: [Object] },
     'mwilkison@gmail.com': { website: [Object] },
     'sandra.f.lombardi@gmail.com': { website: [Object] },
     'margo.r.kulkarni@gmail.com': { website: [Object] },
     'alyssa.frazee@gmail.com': { website: [Object] },
     'samueljpost@gmail.com': { website: [Object] },
     'julienfantin@gmail.com': { website: [Object] },
     'Ted@tedlee.me': { website: [Object] },
     'drrckln@gmail.com': { website: [Object] },
     'lawrence.trey@gmail.com': { website: [Object] },
     'jari@takkala.net': { website: [Object] },
     'grstearns@gmail.com': { website: [Object] },
     'lyndsey@uchicago.edu': { website: [Object] },
     'alexandre.beaulne@gmail.com': { website: [Object] },
     'amandine.m.lee@gmail.com': { website: [Object] },
     'leocadiotine@gmail.com': { website: [Object] },
     'kristenwidman@gmail.com': { website: [Object] },
     'ian@theknown.net': { website: [Object] },
     'Leah.A.Hanson@gmail.com': { website: [Object] },
     'tom@buchok.com': { website: [Object] },
     'rishi2@gmail.com': { website: [Object] },
     'Dlichte5@jhu.edu': { website: [Object] },
     'outofthemadness@gmail.com': { website: [Object] },
     'mail@damonzucconi.com': { website: [Object] },
     'oufei.dong@gmail.com': { website: [Object] },
     'tgebru@gmail.com': { website: [Object] },
     'becca.liss@gmail.com': { website: [Object] },
     'lushili06@gmail.com': { website: [Object] },
     'stefan@karpinski.org': { website: [Object] },
     'porterjamesj@gmail.com': { website: [Object] },
     'jac300@nyu.edu': { website: [Object] },
     'scott@scott.mn': { website: [Object] },
     'emily.sommer@gmail.com': { website: [Object] },
     'zack@zacharymaril.com': { website: [Object] },
     'jeffblagdon@gmail.com': { website: [Object] },
     'romy@romyromy.com': { website: [Object] },
     'jin.chung17@gmail.com': { website: [Object] },
     's@sidneysm.com': { website: [Object] },
     'allie.jones@gmail.com': { website: [Object] },
     'brandon@rhodesmill.org': { website: [Object] },
     'sonali@hackerschool.com': { website: [Object] },
     'sam@samepstein.com': { website: [Object] },
     'tjlahr@gmail.com': { website: [Object] },
     'HolgerSindbaek@gmail.com': { website: [Object] },
     'jyl702@gmail.com': { website: [Object] },
     'carlsednaoui@gmail.com': { website: [Object] },
     'jamie@scattered-thoughts.net': { website: [Object] },
     'hi@ingridcheung.com': { website: [Object] },
     'jdennis@gmail.com': { website: [Object] },
     'jacqueline_stoermer@brown.edu': { website: [Object] },
     'doronr@sas.upenn.edu': { website: [Object] },
     'chemical.rivas@gmail.com': { website: [Object] },
     'jmw@johnmyleswhite.com': { website: [Object] },
     'katerinab@gmail.com': { website: [Object] },
     'jay@jayschwa.net': { website: [Object] },
     'solveig.hansen@gmail.com': { website: [Object] },
     'aroberts@live.unc.edu': { website: [Object] },
     'pnf@podsnap.com': { website: [Object] },
     'jferguson2.718@gmail.com': { website: [Object] },
     'danluu@gmail.com': { website: [Object] },
     'MGD1981@gmail.com': { website: [Object] },
     'kvstewar@gmail.com': { website: [Object] },
     'rupss@cs.stanford.edu': { website: [Object] },
     'tsinha@gmail.com': { website: [Object] },
     'zach.dexter@gmail.com': { website: [Object] },
     'alisa.palson@gmail.com': { website: [Object] },
     'xiayunsun@gmail.com': { website: [Object] },
     'almosteverywhere@gmail.com': { website: [Object] },
     'smar.gonz@gmail.com': { website: [Object] },
     'hs.blaggregator@gmail.com': { website: [Object] },
     'raul.c.jara@gmail.com': { website: [Object] },
     'tomislav@gandzo.com': { website: [Object] },
     'leroux@fezrev.com': { website: [Object] },
     'irving.krauss@gmail.com': { website: [Object] },
     'lfranchi@kde.org': { website: [Object] },
     'me@thomasboyt.com': { website: [Object] },
     'sebastianbauersfeld@gmx.de': { website: [Object] },
     's.abraham@gmail.com': { website: [Object] },
     'nadia@elfarnawani.com': { website: [Object] },
     'n_brei@alum.mit.edu': { website: [Object] },
     'hello@kate.io': { website: [Object] },
     'anton@podviaznikov.com': { website: [Object] },
     'einas.haddad@gmail.com': { website: [Object] },
     'hackerschool@fabian-lischka.de': { website: [Object] },
     'mh.toth@gmail.com': { website: [Object] },
     'blsymph@gmail.com': { website: [Object] },
     'nick@vividx.co.uk': { website: [Object] },
     'kevin@keminglabs.com': { website: [Object] },
     'emmbeezee@gmail.com': { website: [Object] },
     'david.m.lundgren@gmail.com': { website: [Object] },
     'jacob@jacobian.org': { website: [Object] },
     'jczetta@gmail.com': { website: [Object] },
     'daphne.larose@gmail.com': { website: [Object] },
     'rut216@gmail.com': { website: [Object] },
     'sumanah@panix.com': { website: [Object] },
     'karan.tamhane@gmail.com': { website: [Object] },
     'hoffman.nathan89@gmail.com': { website: [Object] },
     'dlp2000@live.com': { website: [Object] },
     'ben@brittain.org': { website: [Object] },
     'nada.amin@gmail.com': { website: [Object] },
     'allison@hackerschool.com': { website: [Object] },
     'jordanorelli@gmail.com': { website: [Object] },
     'tom@hackerschool.com': { website: [Object] },
     'dennismartensson@gmail.com': { website: [Object] },
     'maryrosecook@hackerschool.com': { website: [Object] },
     'swoopej@gmail.com': { website: [Object] },
     'robert.pozoga@gmail.com': { website: [Object] },
     'frontdesk@akmccrate.com': { website: [Object] },
     'lev.berlin@gmail.com': { website: [Object] },
     'nehalita@gmail.com': { website: [Object] },
     'mehul.mandania@gmail.com': { website: [Object] },
     'maria.pacana@gmail.com': { website: [Object] },
     'Dwaynekj@gmail.com': { website: [Object] },
     'paulwang727@gmail.com': { website: [Object] },
     'simon@simonmweber.com': { website: [Object] },
     'pnorvig@google.com': { website: [Object] },
     'ohprecio@gmail.com': { website: [Object] },
     'ekelley@princeton.edu': { website: [Object] },
     'robert.buonpastore@gmail.com': { website: [Object] },
     'travis@mcdem.us': { website: [Object] },
     'hcnewsom@gmail.com': { website: [Object] },
     'steven.ciraolo@gmail.com': { website: [Object] },
     'harrington.richard@gmail.com': { website: [Object] },
     'ariamoraine@gmail.com': { website: [Object] },
     'k.r.langer@gmail.com': { website: [Object] },
     'filippo.valsorda@gmail.com': { website: [Object] },
     'glyph@twistedmatrix.com': { website: [Object] },
     'mlauria@caltech.edu': { website: [Object] },
     'lauren.sperber@gmail.com': { website: [Object] },
     'qqrsmith@gmail.com': { website: [Object] },
     'julia@jvns.ca': { website: [Object] },
     'yminsky@janestreet.com': { website: [Object] },
     'cannon.bea@gmail.com': { website: [Object] },
     'yael@nyu.edu': { website: [Object] },
     'tyler.evan.robertson@gmail.com': { website: [Object] },
     'alex@alexwilson.us': { website: [Object] },
     'davemckenna01@gmail.com': { website: [Object] },
     'stewartwatts@gmail.com': { website: [Object] },
     'erik.taubeneck@gmail.com': { website: [Object] },
     'superjoe30@gmail.com': { website: [Object] },
     'gelstudios@gmail.com': { website: [Object] },
     'alejandrociniglio@gmail.com': { website: [Object] },
     'myf@worldtalks.org': { website: [Object] },
     'sfmoore99@gmail.com': { website: [Object] },
     'peter@gigamonkeys.com': { website: [Object] },
     'marcus@ljungblad.nu': { website: [Object] },
     'eric.q.weinstein@gmail.com': { website: [Object] },
     'pnichols104@gmail.com': { website: [Object] },
     'webyrd@gmail.com': { website: [Object] },
     'sparkleshy@gmail.com': { website: [Object] },
     'ericka.ward@gmail.com': { website: [Object] },
     'dustin.getz@gmail.com': { website: [Object] },
     'timur.ridjanovic@gmail.com': { website: [Object] },
     'kevin.paul.kerr@gmail.com': { website: [Object] },
     'g.s.altman@gmail.com': { website: [Object] },
     'angusb@gmail.com': { website: [Object] },
     'brannerchinese@gmail.com': { website: [Object] },
     'lesliebklein@gmail.com': { website: [Object] },
     'alexander.clare@gmail.com': { website: [Object] },
     'bill@billiamram.com': { website: [Object] },
     'me@oskarth.com': { website: [Object] },
     'katz.stephenj@gmail.com': { website: [Object] },
     'nimrodomer@gmail.com': { website: [Object] },
     'polina.giralt@gmail.com': { website: [Object] },
     'matthew.isabel@gmail.com': { website: [Object] },
     'colinmarc@gmail.com': { website: [Object] },
     'zach@hackerschool.com': { website: [Object] },
     'kye@princeton.edu': { website: [Object] },
     'pgbovine@gmail.com': { website: [Object] },
     'michael@lazerwalker.com': { website: [Object] },
     'jdv@foobar.be': { website: [Object] },
     'bebirchall@gmail.com': { website: [Object] },
     'celeritas@ucla.edu': { website: [Object] },
     'jenna.zeigen@gmail.com': { website: [Object] },
     'sasha.laundy@gmail.com': { website: [Object] },
     'beccabainbridge@gmail.com': { website: [Object] },
     'panfia1@gmail.com': { website: [Object] },
     'trucy.phan@gmail.com': { website: [Object] },
     'cpetzold@gmail.com': { website: [Object] },
     'dave@hackerschool.com': { website: [Object] },
     'al3x@al3x.net': { website: [Object] },
     'daniel@danielespeset.com': { website: [Object] },
     'adamfraser0@gmail.com': { website: [Object] },
     'nabil.hassein@gmail.com': { website: [Object] },
     'nzakharenko@gmail.com': { website: [Object] },
     'coreylynch9@gmail.com': { website: [Object] },
     'jessica.mckellar@gmail.com': { website: [Object] },
     'spurekarcareer@gmail.com': { website: [Object] },
     'omar.rizwan@gmail.com': { website: [Object] },
     'nshen@alum.mit.edu': { website: [Object] },
     'alan@hackerschool.com': { website: [Object] },
     'veriathon@gmail.com': { website: [Object] },
     'joeleedel@gmail.com': { website: [Object] },
     'mw166301@gmail.com': { website: [Object] },
     'me@richardjburton.com': { website: [Object] },
     'artem.titoulenko@gmail.com': { website: [Object] },
     'dan@danielna.com': { website: [Object] },
     'martin@tornwall.net': { website: [Object] },
     'alkhaled.sh@gmail.com': { website: [Object] },
     'kyle.littler@gmail.com': { website: [Object] },
     'jeconnol@gmail.com': { website: [Object] },
     'mel@melchua.com': { website: [Object] },
     'dhbikoff@gmail.com': { website: [Object] },
     'shuxiu.zhou@gmail.com': { website: [Object] },
     'pepijndevos@gmail.com': { website: [Object] },
     'briandignan@gmail.com': { website: [Object] },
     'pieterdevlieger@gmail.com': { website: [Object] },
     'kisha@spunklabs.com': { website: [Object] },
     'beverly.a.lau@gmail.com': { website: [Object] },
     'willson.mock@gmail.com': { website: [Object] },
     'me@bn.ee': { website: [Object] },
     'lindsey@composition.al': { website: [Object] },
     'ceristaggbusiness@gmail.com': { website: [Object] },
     'clemmer.alexander@gmail.com': { website: [Object] },
     'dschobel@gmail.com': { website: [Object] },
     'anna1978@gmail.com': { website: [Object] },
     'wrchapin@gmail.com': { website: [Object] },
     'hey.huyen@gmail.com': { website: [Object] },
     'gideond@gmail.com': { website: [Object] },
     'paolo.moretti85@gmail.com': { website: [Object] },
     'ruby.childs1@gmail.com': { website: [Object] },
     'william.abresch@gmail.com': { website: [Object] },
     'johnjworkman@gmail.com': { website: [Object] },
     'nick@hackerschool.com': { website: [Object] },
     'travis.thieman@gmail.com': { website: [Object] },
     'jtfmumm@gmail.com': { website: [Object] },
     'l.e.albaugh@gmail.com': { website: [Object] },
     'seguraa@bellsouth.net': { website: [Object] },
     'baccou@normalesup.org': { website: [Object] },
     'denisgarci@gmail.com': { website: [Object] },
     'sschirme@gmail.com': { website: [Object] },
     'acolyte.camille@gmail.com': { website: [Object] },
     'ryanvergeront@gmail.com': { website: [Object] },
     'lindzey@gmail.com': { website: [Object] },
     'zallarak@umich.edu': { website: [Object] },
     'ertysdl@gmail.com': { website: [Object] },
     'moshe.bildner@gmail.com': { website: [Object] },
     'raymondsohn@gmail.com': { website: [Object] },
     'brianrubinton@gmail.com': { website: [Object] },
     'andyfchen@gmail.com': { website: [Object] },
     'rob.sicurelli@gmail.com': { website: [Object] },
     'me@sent-hil.com': { website: [Object] },
     'ha.chuck@gmail.com': { website: [Object] },
     'khaullen@gmail.com': { website: [Object] },
     'spacemanaki@gmail.com': { website: [Object] },
     'patrick.m.estabrook@gmail.com': { website: [Object] },
     'liamgriffiths+hackerschool@gmail.com': { website: [Object] },
     'david.nolen@gmail.com': { website: [Object] },
     'david.a.peter@gmail.com': { website: [Object] },
     'Jason.Laster.11@gmail.com': { website: [Object] },
     'astrosilverio@gmail.com': { website: [Object] },
     'zunayed@gmail.com': { website: [Object] },
     'kaizokuace@gmail.com': { website: [Object] },
     'alex.rudnick@gmail.com': { website: [Object] },
     'joystate@me.com': { website: [Object] },
     'santialbo@gmail.com': { website: [Object] },
     'majek04@gmail.com': { website: [Object] },
     'annasheaffer@gmail.com': { website: [Object] },
     'george.w.king@gmail.com': { website: [Object] },
     'yinnie.yinnie@gmail.com': { website: [Object] },
     'ediebeer@gmail.com': { website: [Object] },
     'dan.koslow@gmail.com': { website: [Object] },
     'st.mcgovern@gmail.com': { website: [Object] },
     'hackerschool@sunahsuh.com': { website: [Object] },
     'jhwilner1@gmail.com': { website: [Object] },
     'vladilen.kozin@gmail.com': { website: [Object] },
     'chrisedgemon@gmail.com': { website: [Object] },
     'dsucher@gmail.com': { website: [Object] },
     'pirata@gmail.com': { website: [Object] },
     'sean@siobud.com': { website: [Object] },
     'feivel@sdf.org': { website: [Object] },
     'josh.schneier@gmail.com': { website: [Object] },
     'staceysern@gmail.com': { website: [Object] },
     'karlgusner@gmail.com': { website: [Object] },
     'dcampbell24@gmail.com': { website: [Object] },
     'janelwang2008@gmail.com': { website: [Object] },
     'chad.jablonski@gmail.com': { website: [Object] },
     'pmavfmoura@gmail.com': { website: [Object] },
     'ericfode@gmail.com': { website: [Object] },
     'sitongpeng@gmail.com': { website: [Object] },
     'rozenraukh@gmail.com': { website: [Object] },
     'isabella_norvig@brown.edu': { website: [Object] },
     'chi.lucas@gmail.com': { website: [Object] } },
  msg: '',
  queue_id: '1385217399:918',
  realm_users: 
   [ { is_bot: false,
       email: 'jacob@jacobian.org',
       full_name: 'Jacob Kaplan-Moss' },
     { is_bot: false,
       email: 'hs.blaggregator@gmail.com',
       full_name: 'Blaggregator Bot' },
     { is_bot: false,
       email: 'james.c.shieh@gmail.com',
       full_name: 'James Shieh (F\'12)' },
     { is_bot: false,
       email: 'dcampbell24@gmail.com',
       full_name: 'David Campbell (S\'12)' },
     { is_bot: false,
       email: 'peter@gigamonkeys.com',
       full_name: 'Peter Seibel' },
     { is_bot: false,
       email: 'me@bn.ee',
       full_name: 'Brendan Nee (W\'12)' },
     { is_bot: false,
       email: 'Jason.Laster.11@gmail.com',
       full_name: 'Jason Laster (S\'12)' },
     { is_bot: false,
       email: 'hey.huyen@gmail.com',
       full_name: 'Huyen Tran (F\'12)' },
     { is_bot: false,
       email: 'chemical.rivas@gmail.com',
       full_name: 'Erick Rivas (F\'12)' },
     { is_bot: false,
       email: 'janelwang2008@gmail.com',
       full_name: 'Jane Wang (S\'12)' },
     { is_bot: false,
       email: 'lisa.neigut@gmail.com',
       full_name: 'Lisa Neigut (S\'12)' },
     { is_bot: false,
       email: 'josh.schneier@gmail.com',
       full_name: 'Josh Schneier (F\'12)' },
     { is_bot: false,
       email: 'trucy.phan@gmail.com',
       full_name: 'Trucy Phan (S\'12)' },
     { is_bot: false,
       email: 'HolgerSindbaek@gmail.com',
       full_name: 'Holger Sindbaek (F\'12)' },
     { is_bot: false,
       email: 'coreylynch9@gmail.com',
       full_name: 'Corey Lynch (F\'12)' },
     { is_bot: false,
       email: 'rozenraukh@gmail.com',
       full_name: 'Stan Rozenraukh (F\'12)' },
     { is_bot: false,
       email: 'karlgusner@gmail.com',
       full_name: 'Karl Gusner (F\'11)' },
     { is_bot: false,
       email: 'cpetzold@gmail.com',
       full_name: 'Conner Petzold (F\'12)' },
     { is_bot: false,
       email: 's@sidneysm.com',
       full_name: 'Sidney San Martín (W\'12)' },
     { is_bot: false,
       email: 'jabronson@gmail.com',
       full_name: 'Josh Bronson (W\'12)' },
     { is_bot: false,
       email: 'kristian@whizit.dk',
       full_name: 'Kristian Kristensen (F\'11)' },
     { is_bot: false,
       email: 'Dwaynekj@gmail.com',
       full_name: 'Dwayne Jones (F\'12)' },
     { is_bot: false,
       email: 'dustin.getz@gmail.com',
       full_name: 'Dustin Getz (S\'12)' },
     { is_bot: false,
       email: 'sean@siobud.com',
       full_name: 'Sean DuBois (S\'12)' },
     { is_bot: false,
       email: 'smar.gonz@gmail.com',
       full_name: 'Sarah Gonzalez (S\'12)' },
     { is_bot: false,
       email: 'steven.ciraolo@gmail.com',
       full_name: 'Steven Ciraolo (W\'12)' },
     { is_bot: false,
       email: 'st.mcgovern@gmail.com',
       full_name: 'Sean McGovern (W\'13)' },
     { is_bot: false,
       email: 'alejandrociniglio@gmail.com',
       full_name: 'Alejandro Ciniglio (F\'12)' },
     { is_bot: false,
       email: 'daniel@danielespeset.com',
       full_name: 'Daniel Espeset (W\'13)' },
     { is_bot: false,
       email: 'becca.liss@gmail.com',
       full_name: 'Becca Liss (W\'13)' },
     { is_bot: false,
       email: 'margo.r.kulkarni@gmail.com',
       full_name: 'Margo Kulkarni (W\'13)' },
     { is_bot: false,
       email: 'chad.jablonski@gmail.com',
       full_name: 'Chad Jablonski (F\'12)' },
     { is_bot: false,
       email: 'tsinha@gmail.com',
       full_name: 'Tanoy Sinha (F\'12)' },
     { is_bot: false,
       email: 'panfia1@gmail.com',
       full_name: 'Angela Panfil (W\'13)' },
     { is_bot: false,
       email: 'lushili06@gmail.com',
       full_name: 'Lushi Li (W\'13)' },
     { is_bot: false,
       email: 'yael@nyu.edu',
       full_name: 'Yael Elmatad (S\'12)' },
     { is_bot: false,
       email: 'santialbo@gmail.com',
       full_name: 'Santiago Albo (W\'13)' },
     { is_bot: false,
       email: 'alexander.clare@gmail.com',
       full_name: 'Alexander Clare (S\'12)' },
     { is_bot: false,
       email: 'kristenwidman@gmail.com',
       full_name: 'Kristen Widman (F\'12)' },
     { is_bot: false,
       email: 'willson.mock@gmail.com',
       full_name: 'Willson Mock (S\'13)' },
     { is_bot: false,
       email: 'sam@samepstein.com',
       full_name: 'Sam Epstein (F\'11)' },
     { is_bot: false,
       email: 'dan@danielna.com',
       full_name: 'Dan Na (S\'13)' },
     { is_bot: false,
       email: 'tgebru@gmail.com',
       full_name: 'Timnit Gebru (S\'12)' },
     { is_bot: false,
       email: 'mw166301@gmail.com',
       full_name: 'Matthew Wieler (F\'12)' },
     { is_bot: false,
       email: 'sandra.f.lombardi@gmail.com',
       full_name: 'Sandra Lombardi (F\'12)' },
     { is_bot: false,
       email: 'lev.berlin@gmail.com',
       full_name: 'Lev Berlin (F\'11)' },
     { is_bot: true,
       email: 'xiayunsun-bot@students.hackerschool.com',
       full_name: 'github' },
     { is_bot: false,
       email: 'k.r.langer@gmail.com',
       full_name: 'Rebecca Langer (S\'13)' },
     { is_bot: false,
       email: 'dan.koslow@gmail.com',
       full_name: 'Dan Koslow (S\'13)' },
     { is_bot: false,
       email: 'samueljpost@gmail.com',
       full_name: 'Sam Post (S\'13)' },
     { is_bot: false,
       email: 'isabella_norvig@brown.edu',
       full_name: 'Bella Norvig (S\'13)' },
     { is_bot: false,
       email: 'carlsednaoui@gmail.com',
       full_name: 'Carl Sednaoui (S\'13)' },
     { is_bot: false,
       email: 'kaizokuace@gmail.com',
       full_name: 'Hasen Ahmad (F\'12)' },
     { is_bot: false,
       email: 'jamie@scattered-thoughts.net',
       full_name: 'Jamie Brandon (F\'12)' },
     { is_bot: false,
       email: 'mwilkison@gmail.com',
       full_name: 'MacLane Wilkison (S\'13)' },
     { is_bot: false,
       email: 'yinnie.yinnie@gmail.com',
       full_name: 'Yin Liu (S\'13)' },
     { is_bot: false,
       email: 'doronr@sas.upenn.edu',
       full_name: 'Doron Roberts-Kedes (S\'13)' },
     { is_bot: true,
       email: 'hs-office-hour-bot@students.hackerschool.com',
       full_name: 'Office Hour Bot' },
     { is_bot: false,
       email: 'david.m.lundgren@gmail.com',
       full_name: 'David Lundgren (W\'13)' },
     { is_bot: false,
       email: 'shuxiu.zhou@gmail.com',
       full_name: 'Shuxiu (Cecilia) Zhou (S\'13)' },
     { is_bot: false,
       email: 'tjlahr@gmail.com',
       full_name: 'Thomas Lahr (S\'13)' },
     { is_bot: false,
       email: 'george.w.king@gmail.com',
       full_name: 'George King (S\'13)' },
     { is_bot: false,
       email: 'pnf@podsnap.com',
       full_name: 'Peter Fraenkel (S\'13)' },
     { is_bot: false,
       email: 'rut216@gmail.com',
       full_name: 'Alex Skryl (S\'13)' },
     { is_bot: false,
       email: 'zach@hackerschool.com',
       full_name: 'Zach Allaun' },
     { is_bot: false,
       email: 'jmw@johnmyleswhite.com',
       full_name: 'John Myles White' },
     { is_bot: false,
       email: 'nada.amin@gmail.com',
       full_name: 'Nada Amin' },
     { is_bot: false,
       email: 'tomislav@gandzo.com',
       full_name: 'Tomislav Pesut (S\'13)' },
     { is_bot: false,
       email: 'n_brei@alum.mit.edu',
       full_name: 'Nathan W Brei (W\'13)' },
     { is_bot: false,
       email: 'pmavfmoura@gmail.com',
       full_name: 'Pedro V. Moura (S\'13)' },
     { is_bot: false,
       email: 'amandine.m.lee@gmail.com',
       full_name: 'Amandine Lee (S\'13)' },
     { is_bot: false,
       email: 'jacqueline_stoermer@brown.edu',
       full_name: 'Paige Stoermer (S\'13)' },
     { is_bot: true,
       email: 'lauren-bot@students.hackerschool.com',
       full_name: 'laurenbot' },
     { is_bot: true,
       email: 'github-jplot-bot@students.hackerschool.com',
       full_name: 'Joy Sun' },
     { is_bot: false,
       email: 'joystate@me.com',
       full_name: 'Nadia Yudina (S\'13)' },
     { is_bot: false,
       email: 'pnorvig@google.com',
       full_name: 'Peter Norvig' },
     { is_bot: false,
       email: 'julienfantin@gmail.com',
       full_name: 'Julien Fantin (S\'12)' },
     { is_bot: false,
       email: 'nmichalov@gmail.com',
       full_name: 'Nathan Michalov (W\'12)' },
     { is_bot: false,
       email: 'myf@worldtalks.org',
       full_name: 'Myf Ma (F\'12)' },
     { is_bot: false,
       email: 'sitongpeng@gmail.com',
       full_name: 'Sitong Peng (F\'12)' },
     { is_bot: false,
       email: 'arjan.singh@aya.yale.edu',
       full_name: 'Arjan Singh (S\'12)' },
     { is_bot: false,
       email: 'drrckln@gmail.com',
       full_name: 'Derrick Lin (S\'12)' },
     { is_bot: false,
       email: 'kvstewar@gmail.com',
       full_name: 'Kenya Stewart (F\'12)' },
     { is_bot: false,
       email: 'govindmanian@gmail.com',
       full_name: 'Govind Manian (S\'12)' },
     { is_bot: true,
       email: 'tictactoe-bot@students.hackerschool.com',
       full_name: 'tictactoe' },
     { is_bot: true,
       email: 'akicommitbot-bot@students.hackerschool.com',
       full_name: 'akicommitbot' },
     { is_bot: true,
       email: 'super-bot@students.hackerschool.com',
       full_name: 'superbot' },
     { is_bot: false,
       email: 'kisha@spunklabs.com',
       full_name: 'Kisha Michelle Richardson (F\'12)' },
     { is_bot: false,
       email: 'outofthemadness@gmail.com',
       full_name: 'James A. Keene (S\'12)' },
     { is_bot: false,
       email: 'Ted@tedlee.me',
       full_name: 'Ted Lee (F\'12)' },
     { is_bot: false,
       email: 'alkhaled.sh@gmail.com',
       full_name: 'Sulaiman Alkhaled (S\'13)' },
     { is_bot: false,
       email: 'chi.lucas@gmail.com',
       full_name: 'Lucas Chi (W\'12)' },
     { is_bot: false,
       email: 'ekelley@princeton.edu',
       full_name: 'Ed Kelley (S\'13)' },
     { is_bot: false,
       email: 'gelstudios@gmail.com',
       full_name: 'Eric Romano (W\'13)' },
     { is_bot: false,
       email: 'stefan@karpinski.org',
       full_name: 'Stefan Karpinski' },
     { is_bot: false,
       email: 'me@sent-hil.com',
       full_name: 'Senthil Arivudainambi (F\'12)' },
     { is_bot: false,
       email: 'celeritas@ucla.edu',
       full_name: 'Ryan Koven (F\'12)' },
     { is_bot: false,
       email: 'brandon@rhodesmill.org',
       full_name: 'Brandon Rhodes' },
     { is_bot: false,
       email: 'jyl702@gmail.com',
       full_name: 'Jimmy Li (S\'13)' },
     { is_bot: true,
       email: 'gitpnf-bot@students.hackerschool.com',
       full_name: 'gitbot' },
     { is_bot: true,
       email: 'ewestern-git-bot@students.hackerschool.com',
       full_name: 'ewestern-git' },
     { is_bot: true,
       email: 'victory-bot@students.hackerschool.com',
       full_name: 'victorybot' },
     { is_bot: false,
       email: 'jordanorelli@gmail.com',
       full_name: 'Jordan Orelli (F\'11)' },
     { is_bot: true,
       email: 'github-voldemort-bot@students.hackerschool.com',
       full_name: 'github_voldemort' },
     { is_bot: true,
       email: 'Puerco-bot@students.hackerschool.com',
       full_name: 'commit' },
     { is_bot: true,
       email: 'bitcurry-bot@students.hackerschool.com',
       full_name: 'bitcurry' },
     { is_bot: false,
       email: 'lauren.sperber@gmail.com',
       full_name: 'Lauren Sperber (S\'13)' },
     { is_bot: false,
       email: 'william.abresch@gmail.com',
       full_name: 'Bill Abresch (W\'13)' },
     { is_bot: false,
       email: 'irving.krauss@gmail.com',
       full_name: 'John Krauss (F\'11)' },
     { is_bot: false,
       email: 'sschirme@gmail.com',
       full_name: 'Stefanie Schirmer (S\'12)' },
     { is_bot: false,
       email: 'ha.chuck@gmail.com',
       full_name: 'Chuck Ha (W\'13)' },
     { is_bot: false,
       email: 'me@richardjburton.com',
       full_name: 'Richard Burton (W\'13)' },
     { is_bot: false,
       email: 'ruby.childs1@gmail.com',
       full_name: 'Ruby Childs (F\'12)' },
     { is_bot: false,
       email: 'jin.chung17@gmail.com',
       full_name: 'Jin Chung (W\'13)' },
     { is_bot: false,
       email: 'harrington.richard@gmail.com',
       full_name: 'Richard Harrington (S\'13)' },
     { is_bot: false,
       email: 'g.s.altman@gmail.com',
       full_name: 'Greg Altman (W\'13)' },
     { is_bot: false,
       email: 'danluu@gmail.com',
       full_name: 'Dan Luu (W\'13)' },
     { is_bot: false,
       email: 'al3x@al3x.net',
       full_name: 'Alex Payne' },
     { is_bot: false,
       email: 'artem.titoulenko@gmail.com',
       full_name: 'Artem Titoulenko (S\'11)' },
     { is_bot: true,
       email: 'hharvest-bot@students.hackerschool.com',
       full_name: 'Hadoop Harvester' },
     { is_bot: false,
       email: 'colinmarc@gmail.com',
       full_name: 'Colin Marc (W\'12)' },
     { is_bot: false,
       email: 'veriathon@gmail.com',
       full_name: 'James Wang (S\'13)' },
     { is_bot: false,
       email: 'alex@alexwilson.us',
       full_name: 'Alex Wilson (S\'13)' },
     { is_bot: true,
       email: 'lfranchis-test-bot@students.hackerschool.com',
       full_name: 'Leo\'s Test Bot' },
     { is_bot: true,
       email: 'atestbot-bot@students.hackerschool.com',
       full_name: 'a test bot' },
     { is_bot: false,
       email: 'beverly.a.lau@gmail.com',
       full_name: 'Beverly A. Lau (S\'12)' },
     { is_bot: false,
       email: 'robert.buonpastore@gmail.com',
       full_name: 'Robert Buonpastore (S\'13)' },
     { is_bot: false,
       email: 'ertysdl@gmail.com',
       full_name: 'Erik Seidel (S\'13)' },
     { is_bot: true,
       email: 'yahbfs-bot@students.hackerschool.com',
       full_name: 'yet another haskell brainfuck system' },
     { is_bot: false,
       email: 'Dlichte5@jhu.edu',
       full_name: 'David Lichtenberg (S\'13)' },
     { is_bot: false,
       email: 'ericka.ward@gmail.com',
       full_name: 'Ericka Ward (S\'13)' },
     { is_bot: false,
       email: 'mail@damonzucconi.com',
       full_name: 'Damon Zucconi (S\'13)' },
     { is_bot: true,
       email: 'jamesf-bot2-bot@students.hackerschool.com',
       full_name: 'James Robot Ferguson' },
     { is_bot: true,
       email: 'riskAI-bot@students.hackerschool.com',
       full_name: 'riskAI' },
     { is_bot: false,
       email: 'ediebeer@gmail.com',
       full_name: 'Edith Beer (F\'12)' },
     { is_bot: false,
       email: 'webyrd@gmail.com',
       full_name: 'Will Byrd' },
     { is_bot: false,
       email: 'kevin@keminglabs.com',
       full_name: 'Kevin Lynagh' },
     { is_bot: false,
       email: 'tom@buchok.com',
       full_name: 'Tom Buchok (S\'13)' },
     { is_bot: false,
       email: 'patrick.m.estabrook@gmail.com',
       full_name: 'Patrick Estabrook (W\'13)' },
     { is_bot: false,
       email: 'almosteverywhere@gmail.com',
       full_name: 'Julie Lavoie (S\'13)' },
     { is_bot: false,
       email: 'dennismartensson@gmail.com',
       full_name: 'Dennis Martensson (S\'12)' },
     { is_bot: false,
       email: 'ariamoraine@gmail.com',
       full_name: 'Aria Moraine (F\'12)' },
     { is_bot: false,
       email: 'hi@ingridcheung.com',
       full_name: 'Ingrid Cheung (S\'12)' },
     { is_bot: false,
       email: 'ceristaggbusiness@gmail.com',
       full_name: 'Ceri Stagg (S\'12)' },
     { is_bot: false,
       email: 'dlp2000@live.com',
       full_name: 'Dom Roselli (W\'13)' },
     { is_bot: false,
       email: 'jdennis@gmail.com',
       full_name: 'James Dennis (S\'11)' },
     { is_bot: false,
       email: 'acolyte.camille@gmail.com',
       full_name: 'Camille Misenas (S\'13)' },
     { is_bot: false,
       email: 'hoffman.nathan89@gmail.com',
       full_name: 'Nathan Hoffman (S\'12)' },
     { is_bot: false,
       email: 'romy@romyromy.com',
       full_name: 'Romy Hong (W\'13)' },
     { is_bot: false,
       email: 'zach.dexter@gmail.com',
       full_name: 'Zach Dexter (F\'12)' },
     { is_bot: false,
       email: 'dsucher@gmail.com',
       full_name: 'Danielle E. Sucher (W\'12)' },
     { is_bot: false,
       email: 'paolo.moretti85@gmail.com',
       full_name: 'Paolo Moretti (S\'13)' },
     { is_bot: false,
       email: 'simon@simonmweber.com',
       full_name: 'Simon Weber (S\'13)' },
     { is_bot: false,
       email: 'angusb@gmail.com',
       full_name: 'Angus Burton (F\'12)' },
     { is_bot: false,
       email: 'pieterdevlieger@gmail.com',
       full_name: 'Pieter De Vlieger (F\'12)' },
     { is_bot: false,
       email: 'bebirchall@gmail.com',
       full_name: 'Be Birchall (W\'13)' },
     { is_bot: false,
       email: 'spacemanaki@gmail.com',
       full_name: 'Aki Yamada (S\'13)' },
     { is_bot: false,
       email: 'pnichols104@gmail.com',
       full_name: 'Paul Nichols (F\'12)' },
     { is_bot: false,
       email: 'dhbikoff@gmail.com',
       full_name: 'Derek Bikoff (S\'13)' },
     { is_bot: false,
       email: 'robert.pozoga@gmail.com',
       full_name: 'Robert Pozoga (S\'13)' },
     { is_bot: false,
       email: 'me@oskarth.com',
       full_name: 'Oskar Thorén (F\'12)' },
     { is_bot: false,
       email: 'me@thomasboyt.com',
       full_name: 'Thomas Boyt (W\'13)' },
     { is_bot: false,
       email: 'khaullen@gmail.com',
       full_name: 'Colin Regan (W\'13)' },
     { is_bot: false,
       email: 'nehalita@gmail.com',
       full_name: 'Neha Batra (W\'13)' },
     { is_bot: false,
       email: 'glyph@twistedmatrix.com',
       full_name: 'Glyph Lefkowitz' },
     { is_bot: false,
       email: 'nzakharenko@gmail.com',
       full_name: 'Nina Zakarenko (S\'13)' },
     { is_bot: false,
       email: 'chrisedgemon@gmail.com',
       full_name: 'Chris Edgemon (W\'13)' },
     { is_bot: false,
       email: 'hcnewsom@gmail.com',
       full_name: 'Clint Newsom (W\'13)' },
     { is_bot: false,
       email: 'erik.taubeneck@gmail.com',
       full_name: 'Erik Taubeneck (S\'13)' },
     { is_bot: false,
       email: 'grstearns@gmail.com',
       full_name: 'Greg Stearns (S\'12)' },
     { is_bot: false,
       email: 'majek04@gmail.com',
       full_name: 'Marek Majkowski (W\'13)' },
     { is_bot: false,
       email: 'brianrubinton@gmail.com',
       full_name: 'Brian J. Rubinton (S\'13)' },
     { is_bot: false,
       email: 'lindzey@gmail.com',
       full_name: 'Laura Lindzey (S\'13)' },
     { is_bot: false,
       email: 'vm2355@columbia.edu',
       full_name: 'Victoria Mo (S\'12)' },
     { is_bot: false,
       email: 'ryanvergeront@gmail.com',
       full_name: 'Ryan Vergeront (F\'13)' },
     { is_bot: false,
       email: 's.abraham@gmail.com',
       full_name: 'Sunil Abraham (S\'13)' },
     { is_bot: false,
       email: 'swoopej@gmail.com',
       full_name: 'Julie Swoope (F\'12)' },
     { is_bot: false,
       email: 'dave@hackerschool.com',
       full_name: 'David Albert' },
     { is_bot: false,
       email: 'qqrsmith@gmail.com',
       full_name: 'Russell Smith (W\'13)' },
     { is_bot: false,
       email: 'martin@tornwall.net',
       full_name: 'Martin Törnwall (S\'13)' },
     { is_bot: false,
       email: 'sasha.laundy@gmail.com',
       full_name: 'Sasha Laundy (W\'13)' },
     { is_bot: false,
       email: 'jeconnol@gmail.com',
       full_name: 'John Connolly (W\'12)' },
     { is_bot: false,
       email: 'pfrance@gmail.com',
       full_name: 'Peter France (S\'13)' },
     { is_bot: true,
       email: 'bicho-bot@students.hackerschool.com',
       full_name: 'Bicho, part of Metrics Grimoire' },
     { is_bot: false,
       email: 'davemckenna01@gmail.com',
       full_name: 'Dave McKenna (W\'12)' },
     { is_bot: false,
       email: 'nimrodomer@gmail.com',
       full_name: 'Nimrod Omer (F\'12)' },
     { is_bot: false,
       email: 'polina.giralt@gmail.com',
       full_name: 'Polina Giralt (F\'13)' },
     { is_bot: true,
       email: 'commit-participation-progress-bot@students.hackerschool.com',
       full_name: 'Commit Participation Progress' },
     { is_bot: false,
       email: 'mlauria@caltech.edu',
       full_name: 'Michael Lauria (S\'13)' },
     { is_bot: false,
       email: 'matthew.isabel@gmail.com',
       full_name: 'Matthew Isabel (S\'13)' },
     { is_bot: false,
       email: 'zallarak@umich.edu',
       full_name: 'Zain Allarakhia (W\'12)' },
     { is_bot: false,
       email: 'julianlconnor@gmail.com',
       full_name: 'Julian Connor (S\'11)' },
     { is_bot: false,
       email: 'feivel@sdf.org',
       full_name: 'Feivel Jellyfish (W\'13)' },
     { is_bot: false,
       email: 'kevin.paul.kerr@gmail.com',
       full_name: 'Kevin Kerr (W\'12)' },
     { is_bot: false,
       email: 'tyler.evan.robertson@gmail.com',
       full_name: 'Tyler Robertson (F\'12)' },
     { is_bot: false,
       email: 'johnjworkman@gmail.com',
       full_name: 'John J. Workman (S\'11)' },
     { is_bot: false,
       email: 'raymondsohn@gmail.com',
       full_name: 'Ray Sohn (F\'12)' },
     { is_bot: false,
       email: 'cannon.bea@gmail.com',
       full_name: 'Betsy Cannon (F\'12)' },
     { is_bot: false,
       email: 'ben@brittain.org',
       full_name: 'Ben Brittain (S\'12)' },
     { is_bot: false,
       email: 'ericfode@gmail.com',
       full_name: 'Eric Fode (S\'12)' },
     { is_bot: false,
       email: 'vu2srk@gmail.com',
       full_name: 'Sharadha Ramakrishnan (F\'12)' },
     { is_bot: false,
       email: 'shirmung@gmail.com',
       full_name: 'Shirmung Bielefeld (S\'12)' },
     { is_bot: false,
       email: 'leroux@fezrev.com',
       full_name: 'Muhaimin Ahsan (S\'13)' },
     { is_bot: false,
       email: 'einas.haddad@gmail.com',
       full_name: 'Einas Haddad (W\'13)' },
     { is_bot: false,
       email: 'MGD1981@gmail.com',
       full_name: 'Matthew Gregory Davis (S\'13)' },
     { is_bot: false,
       email: 'emmbeezee@gmail.com',
       full_name: 'Maggie Zhou (S\'13)' },
     { is_bot: true,
       email: 'broadcasts-bot@students.hackerschool.com',
       full_name: 'Broadcasts' },
     { is_bot: false,
       email: 'maryrosecook@hackerschool.com',
       full_name: 'Mary Rose Cook' },
     { is_bot: false,
       email: 'zunayed@gmail.com',
       full_name: 'Zunayed Ali Morsalin (F\'13)' },
     { is_bot: false,
       email: 'adam@adampash.com',
       full_name: 'Adam Pash (F\'13)' },
     { is_bot: false,
       email: 'astrosilverio@gmail.com',
       full_name: 'Katie Silverio (F\'13)' },
     { is_bot: false,
       email: 'jtfmumm@gmail.com',
       full_name: 'John Mumm (F\'13)' },
     { is_bot: false,
       email: 'anna1978@gmail.com',
       full_name: 'Anna Andresian (F\'13)' },
     { is_bot: false,
       email: 'annasheaffer@gmail.com',
       full_name: 'Anna Sheaffer (F\'13)' },
     { is_bot: false,
       email: 'timur.ridjanovic@gmail.com',
       full_name: 'Timur Ridjanovic (F\'13)' },
     { is_bot: false,
       email: 'blsymph@gmail.com',
       full_name: 'Brian Le (F\'13)' },
     { is_bot: false,
       email: 'jczetta@gmail.com',
       full_name: 'Jackie Cohen (S\'12)' },
     { is_bot: false,
       email: 'anton@podviaznikov.com',
       full_name: 'Anton Podviaznikov (F\'13)' },
     { is_bot: false,
       email: 'mh.toth@gmail.com',
       full_name: 'Monica Toth (F\'13)' },
     { is_bot: false,
       email: 'filippo.valsorda@gmail.com',
       full_name: 'Filippo Valsorda (F\'13)' },
     { is_bot: false,
       email: 'moshe.bildner@gmail.com',
       full_name: 'Moshe Bildner (F\'13)' },
     { is_bot: false,
       email: 'katz.stephenj@gmail.com',
       full_name: 'Stephen Katz (F\'13)' },
     { is_bot: false,
       email: 'briandignan@gmail.com',
       full_name: 'Brian Dignan (F\'13)' },
     { is_bot: false,
       email: 'rob.sicurelli@gmail.com',
       full_name: 'Rob Sicurelli (F\'13)' },
     { is_bot: false,
       email: 'jeffblagdon@gmail.com',
       full_name: 'Jeff Blagdon (F\'13)' },
     { is_bot: false,
       email: 'rishi2@gmail.com',
       full_name: 'Rishi Ghosh (F\'13)' },
     { is_bot: false,
       email: 'kyle.littler@gmail.com',
       full_name: 'Kyle Littler (F\'13)' },
     { is_bot: false,
       email: 'gideond@gmail.com',
       full_name: 'Gideon Dresdner (F\'13)' },
     { is_bot: false,
       email: 'karan.tamhane@gmail.com',
       full_name: 'Karan Tamhane (F\'13)' },
     { is_bot: false,
       email: 'aroberts@live.unc.edu',
       full_name: 'Amy Roberts (F\'13)' },
     { is_bot: false,
       email: 'lesliebklein@gmail.com',
       full_name: 'Leslie Klein (F\'13)' },
     { is_bot: false,
       email: 'daphne.larose@gmail.com',
       full_name: 'Daphne Larose (F\'13)' },
     { is_bot: false,
       email: 'oufei.dong@gmail.com',
       full_name: 'Fei Dong (F\'13)' },
     { is_bot: false,
       email: 'nadia@elfarnawani.com',
       full_name: 'Nadia Elfarnawani (F\'13)' },
     { is_bot: false,
       email: 'Leah.A.Hanson@gmail.com',
       full_name: 'Leah Hanson (W\'13)' },
     { is_bot: true,
       email: 'juliagit-bot@students.hackerschool.com',
       full_name: 'juliagit' },
     { is_bot: true,
       email: 'steve-katz-github-bot@students.hackerschool.com',
       full_name: 'Stephen Katz (F\'13)' },
     { is_bot: false,
       email: 'hackerschool@sunahsuh.com',
       full_name: 'Sunah Suh (S\'12)' },
     { is_bot: false,
       email: 'raul.c.jara@gmail.com',
       full_name: 'Raúl Jara (W\'13)' },
     { is_bot: false,
       email: 'paulwang727@gmail.com',
       full_name: 'Paul Wang (F\'13)' },
     { is_bot: false,
       email: 'allison@hackerschool.com',
       full_name: 'Allison Kaptur' },
     { is_bot: false,
       email: 'sfmoore99@gmail.com',
       full_name: 'Sarah Moore (S\'13)' },
     { is_bot: false,
       email: 'alan@hackerschool.com',
       full_name: 'Alan O\'Donnell' },
     { is_bot: false,
       email: 'david.a.peter@gmail.com',
       full_name: 'David Peter (S\'12)' },
     { is_bot: false,
       email: 'liamgriffiths+hackerschool@gmail.com',
       full_name: 'Liam Griffiths (F\'13)' },
     { is_bot: false,
       email: 'nick@hackerschool.com',
       full_name: 'Nick Bergson-Shilcock' },
     { is_bot: false,
       email: 'lindsey@composition.al',
       full_name: 'Lindsey Kuper' },
     { is_bot: false,
       email: 'seguraa@bellsouth.net',
       full_name: 'Alex Segura (F\'13)' },
     { is_bot: false,
       email: 'stewartwatts@gmail.com',
       full_name: 'Stewart Watts (F\'13)' },
     { is_bot: false,
       email: 'jessica.mckellar@gmail.com',
       full_name: 'Jessica McKellar' },
     { is_bot: true,
       email: 'pybgit-bot@students.hackerschool.com',
       full_name: 'github bot' },
     { is_bot: true,
       email: 'test_zulip_cli-bot@students.hackerschool.com',
       full_name: 'Ryan\'s Bot' },
     { is_bot: false,
       email: 'yminsky@janestreet.com',
       full_name: 'Yaron Minsky' },
     { is_bot: true,
       email: 'carmensandiego-bot@students.hackerschool.com',
       full_name: 'Where on the Oregon Trail is Carmen Sandiego?' },
     { is_bot: false,
       email: 'allie.jones@gmail.com',
       full_name: 'Allie Jones (W\'13)' },
     { is_bot: true,
       email: 'alex-bot@students.hackerschool.com',
       full_name: 'alex-bot' },
     { is_bot: false,
       email: 'jhwilner1@gmail.com',
       full_name: 'Joe Wilner (F\'13)' },
     { is_bot: false,
       email: 'travis@mcdem.us',
       full_name: 'Travis McDemus (S\'13)' },
     { is_bot: false,
       email: 'tom@hackerschool.com',
       full_name: 'Tom Ballinger' },
     { is_bot: false,
       email: 'lfranchi@kde.org',
       full_name: 'Leo Franchi (F\'12)' },
     { is_bot: false,
       email: 'l.e.albaugh@gmail.com',
       full_name: 'Lea Albaugh (F\'13)' },
     { is_bot: false,
       email: 'wrchapin@gmail.com',
       full_name: 'Will Chapin (F\'13)' },
     { is_bot: false,
       email: 'beccabainbridge@gmail.com',
       full_name: 'Rebecca Bainbridge (F\'13)' },
     { is_bot: false,
       email: 'lyndsey@uchicago.edu',
       full_name: 'Lyndsey Moulds (F\'13)' },
     { is_bot: true,
       email: 'gitravis-bot@students.hackerschool.com',
       full_name: 'Travis\' github commit bot' },
     { is_bot: false,
       email: 'clemmer.alexander@gmail.com',
       full_name: 'Alex Clemmer (S\'13)' },
     { is_bot: false,
       email: 'spurekarcareer@gmail.com',
       full_name: 'Smita Purekar (F\'13)' },
     { is_bot: false,
       email: 'darius@wry.me',
       full_name: 'Darius Bacon (F\'12)' },
     { is_bot: false,
       email: 'jari@takkala.net',
       full_name: 'Jari Takkala (F\'13)' },
     { is_bot: false,
       email: 'pirata@gmail.com',
       full_name: 'Javier Ernesto Olaechea (S\'13)' },
     { is_bot: true,
       email: 'dude-bot@students.hackerschool.com',
       full_name: 'The Dude' },
     { is_bot: true,
       email: 'becca-bot@students.hackerschool.com',
       full_name: 'becca-bot' },
     { is_bot: true,
       email: '20-20-20-bot@students.hackerschool.com',
       full_name: '20-20-20-bot' },
     { is_bot: false,
       email: 'staceysern@gmail.com',
       full_name: 'Stacey Sern (F\'13)' },
     { is_bot: false,
       email: 'sonali@hackerschool.com',
       full_name: 'Sonali Sridhar' },
     { is_bot: false,
       email: 'ian@theknown.net',
       full_name: 'Ian Whitlock (S\'13)' },
     { is_bot: false,
       email: 'baccou@normalesup.org',
       full_name: 'Pierre-Yves Baccou (F\'13)' },
     { is_bot: false,
       email: 'hackerschool@fabian-lischka.de',
       full_name: 'Fabian Lischka (F\'13)' },
     { is_bot: false,
       email: 'denisgarci@gmail.com',
       full_name: 'Denis Garcia (F\'13)' },
     { is_bot: false,
       email: 'nshen@alum.mit.edu',
       full_name: 'Nancy Shen (F\'13)' },
     { is_bot: false,
       email: 'jay@jayschwa.net',
       full_name: 'Jay Weisskopf (W\'13)' },
     { is_bot: false,
       email: 'travis.thieman@gmail.com',
       full_name: 'Travis Thieman (F\'13)' },
     { is_bot: false,
       email: 'pepijndevos@gmail.com',
       full_name: 'Pepijn de Vos (S\'12)' },
     { is_bot: false,
       email: 'emily.sommer@gmail.com',
       full_name: 'Emily Sommer (F\'13)' },
     { is_bot: false,
       email: 'david.nolen@gmail.com',
       full_name: 'David Nolen' },
     { is_bot: false,
       email: 'katerinab@gmail.com',
       full_name: 'Katerina Barone-Adesi (F\'13)' },
     { is_bot: false,
       email: 'vladilen.kozin@gmail.com',
       full_name: 'Vlad Kozin (F\'13)' },
     { is_bot: false,
       email: 'jdv@foobar.be',
       full_name: 'Jonas De Vuyst (F\'13)' },
     { is_bot: false,
       email: 'omar.rizwan@gmail.com',
       full_name: 'Omar Rizwan (W\'13)' },
     { is_bot: false,
       email: 'michael@lazerwalker.com',
       full_name: 'Mike Walker (F\'13)' },
     { is_bot: true,
       email: 'paca-bot@students.hackerschool.com',
       full_name: 'pacabot' },
     { is_bot: false,
       email: 'hello@kate.io',
       full_name: 'Kate Murphy (F\'13)' },
     { is_bot: false,
       email: 'sparkleshy@gmail.com',
       full_name: 'Alice Monday (S\'13)' },
     { is_bot: true,
       email: 'botastic-bot@students.hackerschool.com',
       full_name: 'Botastic-Supa-Fly' },
     { is_bot: false,
       email: 'leocadiotine@gmail.com',
       full_name: 'Leocadio Tiné (W\'13)' },
     { is_bot: false,
       email: 'marcus@ljungblad.nu',
       full_name: 'Marcus Ljungblad (F\'13)' },
     { is_bot: false,
       email: 'nabil.hassein@gmail.com',
       full_name: 'Nabil Hassein (S\'13)' },
     { is_bot: false,
       email: 'alex.rudnick@gmail.com',
       full_name: 'Alex Rudnick' },
     { is_bot: false,
       email: 'xiayunsun@gmail.com',
       full_name: 'Xiayun (Joy) Sun (S\'13)' },
     { is_bot: true,
       email: 'missing-from-wikipedia-bot@students.hackerschool.com',
       full_name: 'Missing from Wikipedia' },
     { is_bot: true,
       email: 'eliza-2014-bot@students.hackerschool.com',
       full_name: 'eliza-bot' },
     { is_bot: false,
       email: 'joeleedel@gmail.com',
       full_name: 'Joe Del (S\'13)' },
     { is_bot: false,
       email: 'sumanah@panix.com',
       full_name: 'Sumana Harihareswara (F\'13)' },
     { is_bot: true,
       email: 'bouquet-bot@students.hackerschool.com',
       full_name: 'Bouquet ' },
     { is_bot: false,
       email: 'frontdesk@akmccrate.com',
       full_name: 'Ashton McCrate (F\'13)' },
     { is_bot: false,
       email: 'ohprecio@gmail.com',
       full_name: 'Vincent Ohprecio (F\'12)' },
     { is_bot: false,
       email: 'sebastianbauersfeld@gmx.de',
       full_name: 'Sebastian Bauersfeld (S\'13)' },
     { is_bot: false,
       email: 'andyfchen@gmail.com',
       full_name: 'Andrew Chen (W\'12)' },
     { is_bot: false,
       email: 'brannerchinese@gmail.com',
       full_name: 'David Branner (W\'13)' },
     { is_bot: false,
       email: 'adamfraser0@gmail.com',
       full_name: 'Adam Fraser (W\'13)' },
     { is_bot: false,
       email: 'eric.q.weinstein@gmail.com',
       full_name: 'Eric Weinstein (S\'13)' },
     { is_bot: false,
       email: 'alexandre.beaulne@gmail.com',
       full_name: 'Alexandre Beaulne (W\'13)' },
     { is_bot: false,
       email: 'jac300@nyu.edu',
       full_name: 'Jennifer Clark (W\'13)' },
     { is_bot: false,
       email: 'maria.pacana@gmail.com',
       full_name: 'Maria Pacana (F\'13)' },
     { is_bot: false,
       email: 'solveig.hansen@gmail.com',
       full_name: 'Solveig Hakestad Hansen (F\'13)' },
     { is_bot: false,
       email: 'bill@billiamram.com',
       full_name: 'Bill Ramsey (S\'12)' },
     { is_bot: false,
       email: 'julia@jvns.ca',
       full_name: 'Julia Evans (F\'13)' },
     { is_bot: false,
       email: 'pgbovine@gmail.com',
       full_name: 'Philip Guo' },
     { is_bot: false,
       email: 'nick@vividx.co.uk',
       full_name: 'Nick Collins (W\'13)' },
     { is_bot: false,
       email: 'jferguson2.718@gmail.com',
       full_name: 'James Ferguson (S\'13)' },
     { is_bot: false,
       email: 'mel@melchua.com',
       full_name: 'Mel Chua' },
     { is_bot: false,
       email: 'porterjamesj@gmail.com',
       full_name: 'James J. Porter (S\'13)' },
     { is_bot: false,
       email: 'alisa.palson@gmail.com',
       full_name: 'Alisa Palson (S\'13)' },
     { is_bot: false,
       email: 'jenna.zeigen@gmail.com',
       full_name: 'Jenna Zeigen (F\'12)' },
     { is_bot: false,
       email: 'scott@scott.mn',
       full_name: 'Scott Feeney (W\'13)' },
     { is_bot: true,
       email: 'prof-2014-bot@students.hackerschool.com',
       full_name: 'prof-bot' },
     { is_bot: false,
       email: 'zack@zacharymaril.com',
       full_name: 'Zack Maril (S\'13)' },
     { is_bot: false,
       email: 'lawrence.trey@gmail.com',
       full_name: 'Trey Lawrence (S\'12)' },
     { is_bot: true,
       email: 'babar-bot@students.hackerschool.com',
       full_name: 'Babar' },
     { is_bot: false,
       email: 'superjoe30@gmail.com',
       full_name: 'Andrew Kelley (F\'13)' },
     { is_bot: true,
       email: 'katzbot-bot@students.hackerschool.com',
       full_name: 'katzbot' },
     { is_bot: false,
       email: 'mehul.mandania@gmail.com',
       full_name: 'Mehul Mandania (F\'13)' },
     { is_bot: true,
       email: 'Eliza-bot@students.hackerschool.com',
       full_name: 'Eliza-bot' },
     { is_bot: true,
       email: 'stark-bot@students.hackerschool.com',
       full_name: 'Iron Man!' },
     { is_bot: true,
       email: 'bubo-bot@students.hackerschool.com',
       full_name: 'Bubo' },
     { is_bot: true,
       email: 'paul-bot@students.hackerschool.com',
       full_name: 'PaulTestBot' },
     { is_bot: true,
       email: 'test_botty-bot@students.hackerschool.com',
       full_name: 'testBotty' },
     { is_bot: false,
       email: 'kye@princeton.edu',
       full_name: 'Katherine Ye (S\'13)' },
     { is_bot: true,
       email: 'nodejs-bot@students.hackerschool.com',
       full_name: 'Event Machine Bot' },
     { is_bot: false,
       email: 'rupss@cs.stanford.edu',
       full_name: 'Rupa Shankar (F\'13)' },
     { is_bot: false,
       email: 'dschobel@gmail.com',
       full_name: 'Daniel Schobel (W\'13)' },
     { is_bot: false,
       email: 'alyssa.frazee@gmail.com',
       full_name: 'Alyssa Frazee (S\'13)' } ],
  pointer: -1,
  realm_emoji: 
   { hellokitty: 'https://humbug-user-uploads.s3.amazonaws.com/o59r0ehi3NrWh6Dx7GoQ17DnwIFjOM5cVDgk5nKjp6mz33_UfWuHpgOtZEy28u_d60vOkVroJiIicPlh/hello2.png',
     hackerschool: 'https://humbug-user-uploads.s3.amazonaws.com/x5b6MWrs10Tot2AHunakuthIsKzphpFdSQgoHbua8jXmanz_Y6y8sMQM_MaQjMkdDiCUiBmO3JUvpfuf/hackerschool.png' },
  unsubscribed: [] }