CREATE DATABASE IF NOT EXISTS zulip 
  DEFAULT CHARACTER SET utf8 
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE message_requests (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender` VARCHAR(100), 
  `recipients` VARCHAR(255), 
  `message` VARCHAR(255), 
  `type` INT, 
  `alarm_time` DATETIME DEFAULT NULL, 
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `alerted` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);